### ISSUE TITLE
How to install after change in IP address but not as developer ?

### ISSUE THREAD

**Issue by akinnega** [miurahr/picast#11]
How to install and run after modifying setting.ini from clone of you git repository?

**Comment by miurahr** [comment]
Please don't modify distribution's settings.ini. Instead of modifying, please copy it into your working directory and change.
then use command line option defined here: https://github.com/miurahr/picast/blob/master/src/picast/__main__.py#L45

```
--config <your_file_path_to_settings_ini>
```

**Comment by miurahr** [comment]
An option '--config' is not documented.
