### ISSUE TITLE
Default implemented players is not enough

### ISSUE THREAD

**Issue by AntonPanikov** [miurahr/picast#25]
**Is your feature request related to a problem? Please describe.**
Implemented gst and vlc players is nice, but it is hard to use for debugging or if you would like to use some external app for streaming.

**Describe the solution you'd like**
It would be nice to have 3rd alternative to vlc and gst, to just print sink name and do nothing

**Describe alternatives you've considered**
Use some wrapper script, named vls, to simply print sink url argument

**Additional context**
I provided implementation for Nop (No operational) player in this Pull request:
https://github.com/miurahr/picast/pull/21

**Comment by miurahr** [comment]
Thank you for contributions. @AntonPanikov !
