### ISSUE TITLE
No need for p2p find

### ISSUE THREAD

**Issue by AntonPanikov** [miurahr/picast#37]
**Is your feature request related to a problem? Please describe.**
p2p find option does not need to be initiated from both sides, especially if one side is not inviting the other. Since pi side is never looking for clients and never call p2p join, it is not necessary to init p2p find as it is only polluting the wifi network and slow down clients.

**Describe the solution you'd like**
p2p find should be committed for now

**Describe alternatives you've considered**
N/A or setup global reasonable timeouts and delays for p2p find

**Additional context**
N/A

**Comment by miurahr** [comment]
Ok, got it.
