### ISSUE TITLE
Cant start picast

### ISSUE THREAD

**Issue by shad0wcrawl3r** [miurahr/picast#6]
The entire installation goes without a hitch. During the first run python returned "Module not found" which was immediately fixed using pip install. After the install gave a OSError. Not a 
" OSError: /home/pi/.local/lib/python3.7/site-packages/picast/settings.ini "

**Comment by miurahr** [comment]
Do you means that https://github.com/miurahr/picast/blob/master/picast/settings.ini is not installed?
