### ISSUE TITLE
picast.exceptions.WpaException: Can not create P2P Wifi interface.

### ISSUE THREAD

**Issue by kevinchen1223** [miurahr/picast#7]

**Comment by miurahr** [comment]
Please install wpasupplicant package and check /sbin/wpa_cli command exist.
Also you should check whether your wifi adapter working well.

**Comment by kevinchen1223** [comment]
> Please install wpasupplicant package and check /sbin/wpa_cli command exist.
> Also you should check whether your wifi adapter working well.

Yes, everything is installed, when I run lazycast, it can be successfully displayed

**Comment by kevinchen1223** [comment]
And I found that first run lazycast, then run picast, the Raspberry Pi can find p2p devices
