### ISSUE TITLE
TypeError: Addresses must be bytes, got [b'192.168.173.1']. Hint: convert string addresses with socket.inet_pton

### ISSUE THREAD

**Issue by kevinchen1223** [miurahr/picast#8]

**Comment by miurahr** [comment]
Could you upload your picast/settings.ini, log configuration: picast/logging.ini,  logfile /var/tmp/picast.log  if you use default logging setting.

**Comment by kevinchen1223** [comment]
INFO Already set a p2p interface.
DEBUG tvservice: b'[\n{ "code":1, "width":640, "height":480, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":2, "width":720, "height":480, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":3, "width":720, "height":480, "rate":60, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":4, "width":1280, "height":720, "rate":60, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":5, "width":1920, "height":1080, "rate":60, "aspect_ratio":"16:9", "scan":"i", "3d_modes":[] },\n{ "code":16, "width":1920, "height":1080, "rate":60, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":17, "width":720, "height":576, "rate":50, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":18, "width":720, "height":576, "rate":50, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":19, "width":1280, "height":720, "rate":50, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":20, "width":1920, "height":1080, "rate":50, "aspect_ratio":"16:9", "scan":"i", "3d_modes":[] },\n{ "code":31, "width":1920, "height":1080, "rate":50, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":32, "width":1920, "height":1080, "rate":24, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] }\n]\n'
DEBUG tvservice: b'[\n{ "code":4, "width":640, "height":480, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":9, "width":800, "height":600, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":16, "width":1024, "height":768, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":35, "width":1280, "height":1024, "rate":60, "aspect_ratio":"5:4", "scan":"p", "3d_modes":[] },\n{ "code":39, "width":1360, "height":768, "rate":60, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] },\n{ "code":42, "width":1400, "height":1050, "rate":60, "aspect_ratio":"4:3", "scan":"p", "3d_modes":[] },\n{ "code":82, "width":1920, "height":1080, "rate":60, "aspect_ratio":"16:9", "scan":"p", "3d_modes":[] }\n]\n'
DEBUG Start dhcpd server.
DEBUG wpa_cli -i p2p-wlan0-1 wps_pin any 12345678 300

**Comment by kevinchen1223** [comment]
pi@raspberrypi:~/picast/picast-0.2.4 $ ./bin/picast 
INFO Already set a p2p interface.
INFO Already set a p2p interface.
Exception in thread rtsp-server-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/pi/picast/picast-0.2.4/picast/rtspsink.py", line 413, in run
    sd.register()
  File "/home/pi/picast/picast-0.2.4/picast/discovery.py", line 37, in register
    addresses=[self.config.myaddress.encode('ascii')], port=self.config.rtsp_port)
  File "/home/pi/.local/lib/python3.7/site-packages/zeroconf/__init__.py", line 1564, in __init__
    'with socket.inet_pton' % invalid)
TypeError: Addresses must be bytes, got [b'192.168.173.1']. Hint: convert string addresses with socket.inet_pton

**Comment by kevinchen1223** [comment]
https://drive.google.com/file/d/1SfRsXLU-QAwt5VG6qKtkWdVERaEqiUEe/view?usp=sharing

**Comment by miurahr** [comment]
There is no strange log shared.

**Comment by miurahr** [comment]
This error is python error so there is a console log which show a source file name and line number.

**Comment by miurahr** [comment]
Does error happened on here? https://github.com/miurahr/picast/blob/44bbf6fa3272e3f2ad03ff9779daa9b4e1a53b89/src/picast/discovery.py#L37

**Comment by miurahr** [comment]
There is a python-zeroconf project example 
```
    info = ServiceInfo(
        "_http._tcp.local.",
        "Paul's Test Web Site._http._tcp.local.",
        addresses=[socket.inet_aton("127.0.0.1")],
        port=80,
        properties=desc,
        server="ash-2.local.",
    )
```
So, we can be `addresses=[socket.inet_aton(self.config.myaddress)]`

**Comment by dabozz88** [comment]
Received a similar issue. 

INFO Already set a p2p interface.
INFO Already set a p2p interface.
Exception in thread rstp-server-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917 in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/dist-packages/picast/rstpsink.py", line 413, in run
    sd.register()
  File "/usr/lib/python3.7/dist-packages/picast/discovery,py", line 37, in register
    addresses=[self.config.myaddresses.encode('ascii')], port=self.config.rtsp_port)
  File "/usr/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1581, in __init__
    'with socket.inet_pton; % invalid)
TypeError: Address must be in bytes, got [b'192.168.173.1']. Hint: convert string addresses with socket.inet_pton

I'm going to try some debugging myself, but my coding is fairly basic. I'll update with any news.

**Comment by hashimoh** [comment]
I have same error.
Log.
INFO Already set a p2p interface.
INFO Already set a p2p interface.
Exception in thread rtsp-server-0:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/picast/rtspsink.py", line 413, in run
    sd.register()
  File "/usr/local/lib/python3.7/dist-packages/picast/discovery.py", line 37, in register
    addresses=[self.config.myaddress.encode('ascii')], port=self.config.rtsp_port)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1581, in __init__
    'with socket.inet_pton' % invalid)
TypeError: Addresses must be bytes, got [b'192.168.173.1']. Hint: convert string addresses with socket.inet_pton

**Comment by miurahr** [comment]
These are report about older version, and fix has already been released.
